### ISSUE TITLE
[feature request] Use Github Actions instead of (along with) Travis

### ISSUE THREAD

**Issue by fyodorio** [maxime1992/dev-to-git#21]
Using [Github Actions](https://github.com/features/actions) instead of Travis (or as an option to choose) would provide for free (and presumably faster) CI workflow with *private repos*

**Comment by maxime1992** [comment]
Thanks @fyodorio that's a really good idea. I haven't had the time to dig into them though and don't have time right now for that. Would be happy to review a PR if you feel like raising one :+1:

**Comment by PauloGoncalvesBH** [comment]
@maxime1992, put me as an assignee? I will send a PR until the next day.

**Comment by maxime1992** [comment]
Hi guys :) 

Thanks @PauloGoncalvesBH for offering your help :pray:. I'd be super glad to get a PR but before that I'd like to make sure we are all talking about the same thing here?

I'd say we can keep Travis as it was a one time setup here for the publishing of the NPM module.
What I'd like though is a file to have Github action setup for people using this module if they prefer their repo (/blog) to be private.

@fyodorio is it what you had in mind too?

@PauloGoncalvesBH is it what you were thinking of? Because I think such a contribution would fit better in the template here: https://github.com/maxime1992/dev.to rather than this repo

**Comment by maxime1992** [comment]
Also, @beeman wrote an article few days ago: https://dev.to/beeman/automate-your-dev-posts-using-github-actions-4hp3

in case that's of any help :)

**Comment by maxime1992** [comment]
Update here, not 100% related but a little bit.

Travis setup wasn't working anymore on this repo so I migrated to Github Actions to build/publish this project.

We should indeed provide an example to have this as the default to publish blog posts as well instead of Travis :+1: 

@PauloGoncalvesBH are you still interested in making a PR for this?

**Comment by maxime1992** [comment]
I've done it in the template repo though https://github.com/maxime1992/dev.to/blob/master/.github/workflows/main.yml  :heavy_check_mark:
